### PR TITLE
Updated tar and fixed other vulnerabilities

### PR DESCRIPTION
**Pull request by Subbup101**

### CODE REVIEW

**Comment by Subbup101** [comment]
I have deleted .iml file.

When I updated "tar" to latest version, I saw 26 vulnerabilities with 'npm audit' command.

And then executed >npm audit fix , which has cleared all vulnerabilities. For this reason, it has made changes in so many places.

**Comment by Subbup101** [comment]
Unnecessary files are now deleted and branch is up-to-date.

**Comment by janniclas** [comment]
hey @Subbup101 , why did you add the tar dependency in the first place? I don't see any changes in the code base, so I'm not sure why this new dependency has come in.

**Comment by bhermann** [comment]
> hey @Subbup101 , why did you add the tar dependency in the first place? I don't see any changes in the code base, so I'm not sure why this new dependency has come in.

I believe that's a vulnerable transitive dependency that they pinned through the PR.

**Comment by bhermann** [comment]
See: https://github.com/delphi-hub/delphi-management/network/alert/client/package-lock.json/tar/open

**Comment by Subbup101** [comment]
Did I installed any unnecessary dependency? I did not get what was wrong here, I just followed security issues document shared by @bhermann and updated dependencies accordingly.

**Comment by janniclas** [comment]
no, you actually did the recommended thing to manually pin a vulnerable transitive dependency. I was just confused, because now it is, obviously, not listed as vulnerable anymore and I couldn't comprehend why you added the dependency ;)

**Comment by bhermann** [comment]
Closing this for now.

**Pull request closed without merging**
