### PR TITLE
Angular integration (issue #17)

### PR DESCRIPTION
**Pull request by TalalE**
Integrate Angular to scala play.

### CODE REVIEW

**Comment by bhermann** [comment]
Compilation is failing. Please fix this first.

**Comment by TalalE** [comment]
The file application.conf was opened by text editor. I closed it.
I also fixed the error and compilation is working now.

**Comment by bhermann** [comment]
@TalalE have you pushed your changes to branch? 
I see no changes since my comments.

**Comment by TalalE** [comment]
No sorry! Now I pushed the changes.

**Comment by bhermann** [comment]
The build is still failing... are you checking it by running `sbt test` on your machine?

**Comment by TalalE** [comment]
I run it with intellij IDE (run task).

**Comment by TalalE** [comment]
I got the compiling error. I work on it.

**Comment by TalalE** [comment]
The error is fixed.

**Comment by bhermann** [comment]
Good that it compiles now. 
However, I am a bit puzzled as now two webservers are opened. One on port 9000 being the regular Scala Play server which I expected, and then another using npm. What is the purpose of having two webservers running? 
Also, on the standard application the stylesheets and images are no longer available.
We could either discuss here over the weekend or in person on Tuesday. I won't merge it in for now.

**Comment by TalalE** [comment]
We would like to do discuss in Person on Tuesday but since we have time tomorrow, we would like start tomorrow.

**Comment by bhermann** [comment]
I think there are already some point you could work on:

- [ ] The missing style and image files 
- [ ] Reasons if and why two webservers are necessary
- [ ] If they are necessary, how their content could be integrated

**Comment by bhermann** [comment]
You seem to use a different branch for this now, so I'll close this PR. Please open another when you are ready.

**Pull request closed without merging**
