### PR TITLE
Feature/model service

### PR DESCRIPTION
**Pull request by janniclas**
This pull request is made based on the results of https://github.com/delphi-hub/delphi-management/pull/83 so please only merge after this was merged.

This pull request introduces a model service and a store service as an additional abstraction layer. The model layer is used to subscribe to any changes made to the state stored in the store service. This is used to share the information about certain instances with multiple components without making the same server request all over again.

If this, admittedly pretty large request, needs further clarification don't hesitate to ask :) 

This pretty much closes https://github.com/delphi-hub/delphi-management/issues/53

### CODE REVIEW

**Comment by janniclas** [comment]
thx for the additional inquiry @johannesduesing .
In my tests the docker control requests end up at the ir but then I get a docker host error like shown on thursday.
@ishwaryaPaderborn what is your behavior in this case?

state should be reloading I will have a look at that.
Regarding the docker controls, there is an issue open for this, which will be addressed in a future update

**Comment by ishwaryaPaderborn** [comment]
@janniclas as per your suggestion I have cloned all the repositories newly and tested. Below is the result:
1. Able to get the Instances and the Running Instances number in the dashboard
2. Able to 'Add' an Instance for any type of component
3. But unable to 'Stop' or 'Pause' any running Instance (Because this dint work could not test'Delete' an Instance functionality as only 'Stopped' Instance can be deleted) 

@johannesduesing Yes, I also got 404 error for 'Stop' and 'Pause' functionalities. 
I'm not sure if this is because of appending an 'a' with the InstanceId while sending a request, because it was working fine when we tested it a month before. This appending 'a' was implemented by @winniedo because she was facing some issue for sending the 'Instance Id' just as a number.

@winniedo could you please confirm the exact reason for appending 'a' to the 'Insatnce Id'?

**Comment by ishwaryaPaderborn** [comment]
@johannesduesing yes, your guess was correct. :) The probem was because of the 'a'.

I just now tested by removing the 'a' while sending the request to ir for 'start/Stop/play/resume' and the docker functionality works as expected. None of the existing functionalities is broken in the latest test.
Hence, I will raise a new pull request to correct this issue.

**Comment by janniclas** [comment]
@johannesduesing @ishwaryaPaderborn thx for your review and the catch with the invalid url. 
I've merged ishwarya's fix into the develop and also in this branch, so please verify if this branch now has the intended behavior.

**Comment by johannesduesing** [comment]
I checked out the latest version and found the following:
- After adding an instance (which still works) the initial state (*Deploying*) is replaced by *Running* without reloading, so as expected
- Start / Stop / Pause / Resume now reach the registry and are being executed as expected. Still they result in errors in the console (see error message below). These state changes are **not** updated without reloading, **only** the initial change from *Deploying* to *Running* works without reloading.
```
Object { headers: {…}, status: 200, statusText: "OK", url: "http://localhost:8083/api/stopInstance?instanceID=1", ok: false, name: "HttpErrorResponse", message: "Http failure during parsing for http://localhost:8083/api/stopInstance?instanceID=1", error: {…} }
```
- The Delete button does not seem to do anything. Does not work when state is *Stopped*, does not work for any other state, and triggers no messages in the console

**Comment by ishwaryaPaderborn** [comment]
Tested the updated code and found few results:
As reported by @johannesduesing I also found the same result for Adding and Start/Stop/Play/Resume functionalities.
But I was successfully able to 'delete' the added instance. Please find the attached screenshots for 'Delete' functionality

delete_instance 1
delete_instance 2
delete_instance 3

**Comment by janniclas** [comment]
since the observed behavior of both reviewers differ we will postpone this till thursday's meeting where we can hopefully sort things out together.
thx for your work so far @ishwaryaPaderborn  and @johannesduesing

**Comment by johannesduesing** [comment]
Update regarding the latest changes:
 - Delete dialog now works as expected in Firefox
 - *Cancel* button works as expected.

**Comment by janniclas** [comment]
since the remaining bug has nothing to do with the functionality added with this pull request it will be merged now and a ticket opened for the bug.

**Pull request merged**
